server:
  host: "0.0.0.0"
  port: 8080

database:
  driver: "postgres"
  dsn: "host=localhost user=postgres password=postgres dbname=repository port=5433 sslmode=disable"

storage:
  provider: "minio"
  endpoint: "localhost:9000"
  bucket: "repo"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  ssl: false

auth:
  jwt_secret: "supersecretkey"
  token_expiry: "24h"

logging:
  level: "debug"
  format: "json"
