server:
  host: "0.0.0.0"
  port: 8080

database:
  driver: "postgres"
  dsn: "host=localhost user=repo password=secret dbname=repository port=5432 sslmode=disable"

storage:
  provider: "minio"
  endpoint: "localhost:9000"
  bucket: "repository"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  ssl: false

search:
  provider: "bleve"
  index_path: "./data/index"

auth:
  jwt_secret: "supersecretkey"
  token_expiry: "24h"

logging:
  level: "debug"
  format: "json"
